### ISSUE TITLE
AttributeError while trying to run a simulation of a metalloprotein

### ISSUE THREAD

**Issue by lvelasco022** [insilichem/ommprotocol#12]
Hello!

I am trying to run a simulation of a metalloprotein using openmmprotocol, but when the first minimization step starts, it crashes due to the following error:

```
#1/8: eq1_protein [Constrained protein]
   Warning: `constraints` and `constrained_atoms` are incompatible. Removing `constraints` option for this stage.
   Minimizing...
Traceback (most recent call last):
   File "/QFsoft/applic/python/conda/envs/openmm-7.1/bin/ommprotocol", line 11, in <module>
     load_entry_point('ommprotocol==0.1.10', 'console_scripts', 'ommprotocol')()
   File "/QFsoft/applic/python/conda/envs/openmm-7.1/lib/python3.6/site-packages/ommprotocol-0.1.10-py3.6.egg/ommprotocol/__init__.py", line 63, in run_protocol
   File "/QFsoft/applic/python/conda/envs/openmm-7.1/lib/python3.6/site-packages/ommprotocol-0.1.10-py3.6.egg/ommprotocol/md.py", line 85, in protocol
   File "/QFsoft/applic/python/conda/envs/openmm-7.1/lib/python3.6/site-packages/ommprotocol-0.1.10-py3.6.egg/ommprotocol/md.py", line 296, in run
   File "/QFsoft/applic/python/conda/envs/openmm-7.1/lib/python3.6/site-packages/ommprotocol-0.1.10-py3.6.egg/ommprotocol/md.py", line 482, in log_reporter
   File "/QFsoft/applic/python/conda/envs/openmm-7.1/lib/python3.6/site-packages/ommprotocol-0.1.10-py3.6.egg/ommprotocol/md.py", line 559, in system_mass
   File "/QFsoft/applic/python/conda/envs/openmm-7.1/lib/python3.6/site-packages/ommprotocol-0.1.10-py3.6.egg/ommprotocol/md.py", line 559, in <genexpr>
AttributeError: 'NoneType' object has no attribute 'mass'
```

The protein I am working with has some metals, so I parametrized them before generating the prmtop and inpcrd files. After that, I loaded the parameters in xleap and I generated the .prmtop and .inpcrd files without any errors.

I would like to know where the AttributeError comes from, and how to avoid it in order to run the simulation.

Thank you in advance!

**Comment by jaimergp** [comment]
`mass` should be an attribute of an `Element` object, which in this case is `None`. This may be due to a strange element in your topology that OpenMM could not recognize. You might workaround that by disabling the status reporters (progress, log), but other problems might arise along the way... so maybe try to fix the topology first.
